### ISSUE TITLE
Display event locks up the chat window.

### ISSUE THREAD

**Issue by alf000** [herbmillerjr/Celeste#5]
When a event is called like pong or welcome. The display dont return to the chat pane.
![image](https://user-images.githubusercontent.com/11018140/96876258-87afab80-1478-11eb-8042-3f372209e9c2.png)

**Comment by herbmillerjr** [comment]
That's nasty. How are you triggering the events?

**Comment by alf000** [comment]
If there are an error message the terminal, the chat pane locks up.
Like if there was a missing file:
GStreamer; Unable to pause - "file:///home/alf/media/test2.mp3"
Error: "Resource not found."

When proper filename is set, there is no issue.

**Comment by herbmillerjr** [comment]
This sounds like "Triggering an AudioAnnouncePane with an invalid audio file causes it to hang". I'll link the card on Deck to this issue.
